FORMAT: 1A
HOST: https://bicineabbiamo.massi.dev/api

# bicineabbiamo

Simple API to get BikeMi station informations.

## Stations Collection [/{?lat,lon,onlyAvailable,onlyFirstResult}]

### List Stations [GET]

Get available bikes amount and types.

+ Parameters
    + lat: `45.464683238626` (float, optional) - Latitude to search around and sort
    + lon: `9.18879747390747` (float, optional) - Longitude to search around and sort
    + onlyAvailable: `true` (boolean, optional) - Return only stations with available bikes
        + Default: false
    + onlyFirstResult: `true` (boolean, optional) - Return only the first result
        + Default: false
    + onlyActive: `true` (boolean, optional) - Return only active statinos
        + Default: true

+ Response 200 (application/json; charset=utf-8)

        {
            "id": 1,
            "description": "Duomo - lato Via Mengoni",
            "name": "Duomo",
            "latitude": 45.464683238626,
            "longitude": 9.18879747390747,
            "active": true,
            "bikesnumber": 11,
            "slotsnumber": 27,
            "emptyslotcount": 16,
            "bikes": [
                {
                    "count": 11,
                    "type": "NORMAL",
                    "name": "Biciclette"
                },
                {
                    "count": 0,
                    "type": "ELECTRIC",
                    "name": "Biciclette elettriche"
                },
                {
                    "count": 0,
                    "type": "CHILD_SEAT",
                    "name": "Biciclette con seggiolino"
                }
            ]
        }
