name: CI

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  fixups:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Check if there are fixup commits
      run: git log --pretty=format:%s origin/master.. | xargs | grep -v fixup
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check version bump
        run: git diff --diff-filter=M origin/master -- "package.json" | grep "version"
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check changelog update
        run: git diff --name-only origin/master -- | grep CHANGELOG.md
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Enable Corepack
      run: corepack enable
    - name: Install dependencies
      run: yarn install --immutable
    - name: Lint
      run: yarn dlx eslint@^5.1.0 .
    - name: Run tests
      env:
        APIARY_API_KEY: ${{ secrets.APIARY_API_KEY }}
        APIARY_API_NAME: ${{ secrets.APIARY_API_NAME }}
        CI: GITHUB_ACTIONS
        NEW_RELIC_NO_CONFIG_FILE: true
        NEW_RELIC_ENABLED: false
        NEW_RELIC_LOG: /dev/null
        ROLLBAR_KEY: ${{ secrets.ROLLBAR_KEY }}
      run: yarn dlx dredd@^5.1.11
