name: Deploy

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
    - name: Report deploy on GitHub
      run: |
              echo DEPLOYMENT_ID=$(echo '{"ref":"master","required_contexts":[]}' | curl -X POST \
              -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              -H content-type:application/json -H accept:application/vnd.github.ant-man-preview+json \
              https://api.github.com/repos/$GITHUB_REPOSITORY/deployments -d @- | jq -r .id) >> $GITHUB_ENV
    - name: Update deploy on GitHub
      run: |
              echo '{"state":"success"}' | curl -X POST \
              -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              -H content-type:application/json -H accept:application/vnd.github.ant-man-preview+json \
              https://api.github.com/repos/$GITHUB_REPOSITORY/deployments/$DEPLOYMENT_ID/statuses -d @- | jq -r
    - name: Report deploy on Rollbar
      run: echo '{"environment":"production","revision":"'$GITHUB_SHA'","rollbar_username":"'$GITHUB_ACTOR'"}' | curl -X POST -H x-rollbar-access-token:${{ secrets.ROLLBAR_API_KEY }} https://api.rollbar.com/api/1/deploy -d @-
