name: Docker

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set env vars
      run: |
        echo DOCKER_PUSH=$([[ $GITHUB_REF == *"master"* ]] && echo "true" || echo "false") >> $GITHUB_ENV
        echo VERSION_NUMBER=$(jq -r < package.json .version) >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker build
      uses: docker/build-push-action@v6
      with:
        tags: maxcanna/bicineabbiamo:latest,maxcanna/bicineabbiamo:${{ env.VERSION_NUMBER }}
        labels: version=$VERSION_NUMBER
        push: ${{ env.DOCKER_PUSH }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
